### ISSUE TITLE
issue in Publish Docker Container workflow  puDEVWF-T007-SBS.md

### ISSUE THREAD

**Issue by himanshuahlawat31** [XpiritBV/CodeToCloud-Student#1]
HI , there has been update in Publish Docker Container workflow as the commands are changed , can you please take a look into this as instructions don't match with latest workflow

**Comment by cdijkstra** [comment]
Hi there, I'm investigating the issue.

**Comment by cdijkstra** [comment]
The new description and solution has been provided [here](https://github.com/XpiritBV/CodeToCloud-Workshop/commit/48387b36e0ccb56750ef439c1f2e9f4b30cef29c). The description is now in alignment with the template that Github provides. 

The Youtube video is still based on the old template, this information has been added: https://github.com/XpiritBV/CodeToCloud-Workshop/commit/77b7a739e516770cd267784e93e6cd80cd93a6cf.
