### ISSUE TITLE
Issue in DEVWF-T005

### ISSUE THREAD

**Issue by anushabc** [XpiritBV/CodeToCloud-Student#2]
As per instructions in DEVWF-T005 step 6, we should be able to see handlebar vulnerability but this step is automatically done we were not able to see handlebars we were not able to find Create Dependabot Security update button.  Can you please take a look into this

**Comment by cdijkstra** [comment]
Are you sure the handlebar dependency alert is not on Page 2/3 of the alerts?
![image](https://user-images.githubusercontent.com/62383372/124609254-c2733b80-de6f-11eb-9a76-5734362287f3.png)

I have deleted my CodeToCloud Source repository and forked it again. I see the alert and can create the  Dependabot Security update
![image](https://user-images.githubusercontent.com/62383372/124609509-f6e6f780-de6f-11eb-82cd-a90d8d424f56.png)
